version: '3.7'

services:
    vue:
        build: ./docker/config/vue
        volumes:
            - ./vue:/vue
        ports:
            - "8080:8080"
        networks:
            - vue_crm_network

networks:
    vue_crm_network:
        driver: bridge
